


export const RESTART_PERIPHERAL_SCAN = 'RESTART_PERIPHERAL_SCAN'
export const CONNECTION_STATUS_CHANGED = 'app.CONNECTION_STATUS_CHANGED'
export const SET_CONNECTION_TIMEOUT = 'app.SET_CONNECTION_TIMEOUT'
export const WRITE_LOG = 'app.WRITE_LOG'
export const TOGGLE_DEBUG_MODE = 'app.TOGGLE_DEBUG_MODE'
export const TOGGLE_DEBUG_INTERFACE = 'app.TOGGLE_DEBUG_INTERFACE'
export const TOGGLE_POPUP_MODE = 'app.TOGGLE_POPUP_MODE'
export const CLEAR_LOG = 'app.CLEAR_LOG'
export const SET_PERIPHERALS = 'app.SET_PERIPHERALS'
export const PAIR_PERIPHERAL = 'app.PAIR_PERIPHERAL'
export const UNPAIR_PERIPHERAL = 'app.UNPAIR_PERIPHERAL'
export const UPDATE_PROGRAM_LOCALLY = 'app.UPDATE_PROGRAM_LOCALLY'
export const CHANGE_VALVE_STATUS_LOCALLY = 'app.CHANGE_VALVE_STATUS_LOCALLY'
export const SET_PERIPHERAL = 'app.SET_PERIPHERAL'
export const SET_PERIPHERAL_CONNECTION = 'app.SET_PERIPHERAL_CONNECTION'
export const SET_APP_STATE = 'app.SET_APP_STATE'
export const USING_24HOUR_FORMAT = 'app.USING_24HOUR_FORMAT'
export const DEVICE_VALVES_UPDATE = 'app.DEVICE_VALVES_UPDATE'


