export default NavigationsIcons = {
    bluetoothOn: require("../Assets/Images/bluetoothOn.png"),
    bluetoothOff: require("../Assets/Images/bluetoothOff.png"),
    menu: require("../Assets/Images/menu.png"),
    galcon: require("../Assets/Images/galcon.png"),
    timers: require("../Assets/Images/timers.png"),
    market: require("../Assets/Images/market.png"),
    info: require("../Assets/Images/info.png"),
    contact: require("../Assets/Images/contact.png"),
    manual: require("../Assets/Images/manual.png"),
    program: require("../Assets/Images/program.png"),
    status: require("../Assets/Images/status.png"),
    batteryEmpty:require("../Assets/Images/battery/empty.png"),
    batteryLow:require("../Assets/Images/battery/low.png"),
    batteryOk:require("../Assets/Images/battery/ok.png"),
    back: require("../Assets/Images/back.png"),
    clear: require("../Assets/Images/clear.png"),
    updateToTimer: require("../Assets/Images/updateToTimer.png"),
    updateToApp: require("../Assets/Images/updateToApp.png"),
    rainOff: require("../Assets/Images/rainOff.png"),
    refresh:require("../Assets/Images/refresh.png"),
    valve:require("../Assets/Images/valve.png"),
    arrowDropDown:require("../Assets/Images/arrowDropDown.png"),
}